name: cfDNA_project
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
  - bioconda
  - genomedk
  - gwforg
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - amply=0.1.6=py312h06a4308_1
  - annotated-types=0.6.0=py312h06a4308_0
  - aom=3.12.1=h7934f7d_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - arrow-cpp=21.0.0=hac1acdb_1
  - attrs=24.3.0=py312h06a4308_0
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py312ha883a20_0
  - brotlicffi=1.0.9.2=py312h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=py312h06a4308_0
  - cffi=1.17.1=py312h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py312h06a4308_0
  - coin-or-cbc=2.10.10=hd28fd6d_0
  - coin-or-cgl=0.60.5=h3cb4718_0
  - coin-or-clp=1.17.7=h4e0f3ec_0
  - coin-or-osi=0.108.7=h3cb4718_0
  - coin-or-utils=2.11.6=h4e0f3ec_0
  - coloredlogs=15.0.1=py312h06a4308_3
  - conda-inject=1.3.2=pyhd8ed1ab_0
  - configargparse=1.7.1=py312h06a4308_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.3.3=py312hdb19cb5_0
  - dav1d=1.2.1=h5eee18b_0
  - docutils=0.21.2=py312h06a4308_0
  - dpath=2.2.0=pyha770c72_0
  - eido=0.2.4=pyhd8ed1ab_0
  - fontconfig=2.15.0=h7e30c49_1
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gettext=0.21.0=hedfda30_2
  - gflags=2.2.2=h6a678d5_1
  - gitdb=4.0.12=py312h06a4308_0
  - gitpython=3.1.43=py312h06a4308_0
  - glog=0.5.0=h6a678d5_1
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - humanfriendly=10.0=py312h06a4308_2
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - immutables=0.21=py312hee96239_0
  - iniconfig=2.1.0=py312h06a4308_0
  - jansson=2.14=h5eee18b_1
  - jinja2=3.1.6=py312h06a4308_0
  - joblib=1.5.2=py312h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - jsonschema=4.25.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter_core=5.8.1=py312h06a4308_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h0131e85_1
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.1.0=h767d61c_5
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.29=ha39b09d_0
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.50=h2ed474d_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.22.0=hd8eb582_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=2.41.1=he9a06e4_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - logmuse=0.2.8=pyhd8ed1ab_1
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=4.0.0=py312h06a4308_0
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib-base=3.10.6=py312h71dd3da_1
  - mdurl=0.1.0=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - nbstripout=0.8.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - numexpr=2.11.0=py312hccd6f0b_1
  - numpy=1.26.4=py312hc213724_1
  - numpy-base=1.26.4=py312hf387b04_1
  - openssl=3.5.2=h26f9b46_0
  - orc=2.2.0=h372e9aa_0
  - packaging=25.0=py312h06a4308_0
  - pandas=2.3.2=py312h277b779_0
  - pcre2=10.46=hf426167_0
  - pephubclient=0.4.4=pyhd8ed1ab_1
  - peppy=0.40.7=pyhd8ed1ab_2
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - plac=1.4.5=py312h06a4308_0
  - platformdirs=4.3.7=py312h06a4308_0
  - pluggy=1.5.0=py312h06a4308_0
  - psutil=7.0.0=py312hee96239_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pulp=2.8.0=py312hd0750ca_2
  - pyarrow=21.0.0=py312h505adc9_0
  - pycparser=2.23=py312h06a4308_0
  - pydantic=2.11.7=py312h06a4308_0
  - pydantic-core=2.33.2=py312hc6f7160_0
  - pygments=2.19.1=py312h06a4308_0
  - pyparsing=3.2.0=py312h06a4308_0
  - pysocks=1.7.1=py312h06a4308_0
  - pytest=8.4.1=py312h06a4308_0
  - python=3.12.11=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.12=1_cp312
  - pytz=2025.2=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.32.5=py312h06a4308_0
  - reretry=0.11.8=pyhd8ed1ab_1
  - rich=13.9.4=py312h06a4308_0
  - rpds-py=0.22.3=py312h4aa5aa6_0
  - s2n=1.5.14=hdbd6064_0
  - scikit-learn=1.7.2=py312h505adc9_0
  - scipy=1.16.1=py312ha592af2_0
  - seaborn=0.13.2=py312h06a4308_3
  - setuptools=78.1.1=py312h06a4308_0
  - shellingham=1.5.0=py312h06a4308_0
  - six=1.17.0=py312h06a4308_0
  - slack-sdk=3.36.0=py312h06a4308_0
  - slack_sdk=3.36.0=py312h06a4308_0
  - smart_open=7.3.1=py312h06a4308_0
  - smmap=5.0.2=py312h06a4308_0
  - snakemake=9.11.2=hdfd78af_0
  - snakemake-executor-plugin-slurm=1.7.0=pyhdfd78af_0
  - snakemake-executor-plugin-slurm-jobstep=0.3.0=pyhdfd78af_0
  - snakemake-interface-common=1.21.0=pyhdfd78af_0
  - snakemake-interface-executor-plugins=9.3.9=pyhdfd78af_0
  - snakemake-interface-logger-plugins=1.2.4=pyhdfd78af_0
  - snakemake-interface-report-plugins=1.2.0=pyhdfd78af_0
  - snakemake-interface-scheduler-plugins=2.0.1=pyhd4c3c12_0
  - snakemake-interface-storage-plugins=4.2.2=pyhdfd78af_0
  - snakemake-minimal=9.11.2=pyhdfd78af_0
  - snappy=1.2.1=h6a678d5_0
  - tabulate=0.9.0=py312h06a4308_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.15=h54e0aa7_0
  - traitlets=5.14.3=py312h06a4308_0
  - typer=0.17.4=py312h06a4308_0
  - typing-extensions=4.15.0=py312h06a4308_0
  - typing-inspection=0.4.0=py312h06a4308_0
  - typing_extensions=4.15.0=py312h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - urllib3=2.5.0=py312h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - veracitools=0.1.3=py_0
  - wheel=0.45.1=py312h06a4308_0
  - wrapt=1.17.0=py312h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7b6447c_0
  - yte=1.8.1=pyha770c72_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - cycler==0.12.1
      - fonttools==4.60.0
      - kiwisolver==1.4.9
      - pillow==11.3.0
