# cfDNA Project Configuration
env_name: "cfDNA_project"

input_frags_dir: "../raw_data/cristiano_healthy/"
input_dhs_dir: "../raw_data/lymphoid_dhs/"
sorted_frags_dir: "../raw_data/cristiano_healhty_sorted/"
sorted_dhs_dir: "../raw_data/lymphoid_dhs_sorted/"
hg_38_2bit_file: "../raw_data/hg38.2bit"
output_dir: "../data/cristiano_healhty/"

matrix_columns: 2500
matrix_shift: 250
matrix_rows: 300
hardcut_off_lower: 159000
dhs_gc_bias_window: 200

train_size: 80
valid_size: 10
batch_size: 32