# cfDNA Project Configuration
env_name: "cfDNA_project"

input_dir: "../raw_data/cristiano_cfdnas/"
input_dhs_dir: "../raw_data/dhs_small/"
result_sorted_dir: "../data/sorted/"
result_dir: "../data/cristiano_cfdnas_dhs_small/"
result_pca_dir: "../data/cristiano_cfdnas_dhs_small_pca/"

# input_dir: "../raw_data/test_small/"
# input_dhs_dir: "../raw_data/dhs_small/"
# result_sorted_dir: "../data/sorted/"
# result_dir: "../data/test_small/"
# result_pca_dir: "../data/test_small_pca/"

example_dhs: "Lymphoid_DHS"
example_sample: "EE88171"
metadata_path: "../raw_data/cristiano_cfdnas/meta_data.csv"
paper: "Genome-wide cell-free DNA fragmentation in patients with cancer"

# matrix dimensions
matrix_rows: 500
matrix_columns: 4500
matrix_shift: 250
hardcut_off_lower: 400000  # for downsampling

# L-WPS test statistic parameters
lwps:
  window_size: 120
  lower_threshold: 120
  upper_threshold: 180
  
# FDI test statistic parameters
fdi:
  window_size: 250
  step_size: 20
  endpoint_window: 10
  x: 0.9
  y: 500
  matrix_shift: 250
  
# IFS test statistic parameters
ifs:
  window_size: 125
  matrix_shift: 250

# PFE test statistic parameters
pfe:
  window_size: 4000
  min_length: 100
  max_length: 300
  matrix_shift: 250
  
# OCF test statistic parameters
ocf:
  window_half: 10
  center_offset: 60
  matrix_shift: 250